name: Cypress Cloud

on: 
  workflow_dispatch: 
    inputs: 
      spec: 
        description: Run by cypress command line
        default: cypress/e2e/* 

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with:
          install-comand: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHBUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
